### ISSUE TITLE
Element type is not valid.

### ISSUE THREAD

**Issue by eldyvoon** [atulmy/node-express-react-redux-zwitter#1]
I got this error

http://i.imgur.com/MhK0FT1.png

**Comment by atulmy** [comment]
Fixed the react-router": "4.0.0-alpha.6",. This resolved the issue.

**Comment by atulmy** [comment]
Updated react router from v4.0.0-aplha.6 to v4.1.1 (now using `react-router-dom` instead of `react-router`)
