### ISSUE TITLE
Example.env

### ISSUE THREAD

**Issue by moafzalmulla** [atulmy/node-express-react-redux-zwitter#2]
Hello there

Great repo, both api and frontend

I cloned and followed instructions but has some issues on login.

Can you possibly include example.env file ?

**Comment by atulmy** [comment]
@tweetzal there is no `.env` required to run it locally. 

Just make modifications to: `api/src/config/index.js` and `frontend/src/config/index.js` in case you want to set it up for production.

However in case you are looking for `.env` based configurations, check out https://github.com/atulmy/wispy/blob/master/web/src/setup/config/env.js and an example here https://github.com/atulmy/wispy/blob/master/web/.env.local
